CREATE TABLE BOARD (
	BNO	INT unsigned PRIMARY KEY auto_increment,
    TITLE VARCHAR(100)	NOT NULL,
    CONTENT VARCHAR(4000) NOT NULL,
    WRITER VARCHAR(50)	NOT NULL,
    REGDATE datetime DEFAULT NOW(),
    UPDATEDATE datetime NULL,
    VIEWCOUNT INT unsigned DEFAULT 0
);